/**
 * Content Templates for Auto-Promoter
 * Project-specific content for better engagement
 */

/**
 * Badge Generator Content
 */
export const badgeGenerator = {
  devto: {
    title: 'Complete GitHub Badge Reference — Copy, Paste, Done',
    description: 'The complete badge reference for your GitHub README. 500+ badges, all CDN-hosted, free forever.',
    body: `# GitHub Badge Generator

The complete badge reference for your GitHub README. All badges are SVG-based, CDN-hosted, and free forever.

## Why This Project?

Most badge references are incomplete or scattered across multiple sites. This project brings together:

- **500+ badge examples** — All in one place
- **CDN-hosted** — Via Shields.io, no hosting needed
- **Copy-paste** — No editing required
- **Organized** — Logical categories for easy browsing

## Quick Start

\`\`\`markdown
[![Status](https://img.shields.io/badge/status-active-success)]()
[![License](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
\`\`\`

## Categories

| Category | Examples |
|----------|----------|
| Status | Active, Beta, Deprecated, Stable |
| Version | npm, PyPI, Cargo, Go |
| License | MIT, Apache, GPL, MPL |
| Platform | AWS, Vercel, Cloudflare, Railway |
| Language | JS, TS, Python, Rust, Go, Java |
| Build | GitHub Actions, CI, Tests |
| Quality | CodeFactor, Lint, Coverage |
| Social | Stars, Forks, Followers |
| Funding | GitHub Sponsors, Patreon |

## What Makes This Different

1. **Comprehensive** — Covers all major badge types
2. **Organized** — Logical categorization
3. **Ready to Use** — Copy the code, paste in your README
4. **Always Updated** — Live badges that show current status

## Use Cases

- **Open Source Projects** — Show build status, version, license
- **SaaS Products** — Display uptime, response time
- **Documentation Sites** — Add visual indicators
- **Personal Portfolios** — Showcase skills and tech stack

## Examples

\`\`\`markdown
# My Project

[![Status](https://img.shields.io/badge/status-active-success)]()
[![npm](https://img.shields.io/npm/v/my-package)](https://www.npmjs.com/package/my-package)
[![License](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

My awesome project description.
\`\`\`

## Links

- [GitHub Repository](https://github.com/ozxc44/badge-generator)
- [Full Reference](https://github.com/ozxc44/badge-generator#readme)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['javascript', 'github', 'opensource', 'webdev', 'documentation', 'badges', 'readme', 'developer-tools']
  },

  bluesky: {
    text: `🚀 Just published: GitHub Badge Generator

The complete badge reference for your README.

500+ badges, CDN-hosted, free forever.

github.com/ozxc44/badge-generator

#opensource #javascript #github #developer-tools`
  },

  mastodon: {
    status: `🚀 Just published: GitHub Badge Generator

The complete badge reference for your README. 500+ badges, all CDN-hosted, free forever.

github.com/ozxc44/badge-generator

#opensource #javascript #GitHub #developer-tools`
  },

  discord: {
    description: 'The complete badge reference for your GitHub README. 500+ badges, all CDN-hosted, free forever.'
  }
};

/**
 * Status Badge 2.0 Content
 */
export const statusBadge2 = {
  devto: {
    title: 'Status Badge 2.0 — Serverless Monitoring Widget',
    description: 'Zero-config status monitoring with Cloudflare Workers. Free forever, 100K requests/day.',
    body: `# Status Badge 2.0

A drop-in status widget for any website or API. One line of JavaScript, and you get real-time status monitoring.

## Why Status Badge 2.0?

Most status page solutions are overkill for simple monitoring. Status Badge 2.0 is:

- **Zero Infrastructure** — Runs on Cloudflare Workers edge
- **Free Forever** — 100K requests/day on free tier
- **One-Line Embed** — \`<script src="..."></script>\` and done
- **Shadow DOM** — Styles won't break your site
- **Edge-Fast** — Global CDN, <50ms responses

## Quick Start

### 1. Create a Monitor

\`\`\`bash
curl -X POST https://your-worker.workers.dev/api/monitors \\
  -H "Content-Type: application/json" \\
  -d '{"targetUrl": "https://api.example.com/health", "name": "My API"}'
\`\`\`

### 2. Embed on Your Site

\`\`\`html
<script src="https://your-worker.workers.dev/v1/YOUR_ID.js"></script>
\`\`\`

That's it! The badge shows:
- ✅ Current status (Online/Offline)
- ⏱️ Response time
- 📊 Uptime percentage (24h)

## Architecture

\`\`\`
User's Website
    ↓
<script src="badge.js">
    ↓
Shadow DOM Widget
    ↓
Cloudflare Worker (Edge)
    ↓
Cloudflare KV (Cache)
    ↓
Target API
\`\`\`

## Features

| Feature | Description |
|---------|-------------|
| Real-time | Updates every 60 seconds |
| Themes | Default, Dark, Minimal |
| JSON API | Get status data for custom UI |
| SVG Badge | Image format for READMEs |
| Webhooks | Coming soon |

## Use Cases

- **API Status** — Monitor REST/GraphQL endpoints
- **SaaS Dashboard** — Show service status to customers
- **CI/CD** — Display build/deployment status
- **Microservices** — Monitor multiple services

## Links

- [GitHub Repository](https://github.com/ozxc44/status-badge-2)
- [Live Demo](https://ozxc44.github.io/status-badge-2/)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['javascript', 'cloudflare', 'workers', 'serverless', 'monitoring', 'uptime', 'devops', 'api']
  },

  bluesky: {
    text: `🚀 Status Badge 2.0 — Serverless monitoring widget

One line of JavaScript = real-time status monitoring.

Runs on Cloudflare Workers edge.
Free forever (100K requests/day).

github.com/ozxc44/status-badge-2

#serverless #cloudflare #monitoring #javascript`
  },

  mastodon: {
    status: `🚀 Status Badge 2.0 — Serverless monitoring widget

One line of JavaScript gives you real-time status monitoring. Runs on Cloudflare Workers edge, free forever (100K requests/day).

github.com/ozxc44/status-badge-2

#serverless #Cloudflare #monitoring #JavaScript`
  },

  discord: {
    description: 'One-line JavaScript widget for real-time status monitoring. Runs on Cloudflare Workers edge, free forever.'
  }
};

/**
 * DocuAPI Content
 */
export const docuapi = {
  devto: {
    title: 'DocuAPI — Generate API Docs from OpenAPI Specs',
    description: 'CLI tool to generate beautiful API documentation from OpenAPI/Swagger specs.',
    body: `# DocuAPI

Generate beautiful API documentation from OpenAPI/Swagger specifications. Perfect for REST APIs, microservices, and backend services.

## Why DocuAPI?

Writing API documentation is tedious. DocuAPI automates it:

- **From OpenAPI** — Import existing specs
- **Beautiful Output** — Clean, readable HTML docs
- **Multiple Formats** — HTML, Markdown, PDF
- **Searchable** — Full-text search included
- **Host Anywhere** — Static files, no database needed

## Quick Start

\`\`\`bash
# Install
npm install -g docuapi

# Generate docs
docuapi generate openapi.json -o docs/

# Serve locally
docuapi serve docs/
\`\`\`

## Features

| Feature | Description |
|---------|-------------|
| OpenAPI 3.0 | Full specification support |
| Multiple Output | HTML, Markdown, PDF |
| Search | Client-side full-text search |
| Themes | Light/dark mode included |
| Examples | Auto-generate from specs |

## Input Example

\`\`\`yaml
openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: Success
\`\`\`

## Links

- [GitHub Repository](https://github.com/ozxc44/docuapi)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['api', 'documentation', 'openapi', 'swagger', 'cli', 'developer-tools', 'rest']
  },

  bluesky: {
    text: `🚀 DocuAPI — Generate API docs from OpenAPI specs

CLI tool that creates beautiful documentation from your OpenAPI/Swagger specs.

Supports HTML, Markdown, PDF outputs.

github.com/ozxc44/docuapi

#api #documentation #openapi #developer-tools`
  },

  mastodon: {
    status: `🚀 DocuAPI — Generate API docs from OpenAPI specs

CLI tool that creates beautiful documentation from your OpenAPI/Swagger specs. Supports HTML, Markdown, PDF outputs.

github.com/ozxc44/docuapi

#API #documentation #OpenAPI #developer-tools`
  },

  discord: {
    description: 'CLI tool to generate beautiful API documentation from OpenAPI/Swagger specifications.'
  }
};

/**
 * Cron Monitor Content
 */
export const cronMonitor = {
  devto: {
    title: 'Cron Monitor — Free Self-Hosted Alternative to Healthchecks.io',
    description: 'Self-hosted cron job monitoring with Cloudflare Workers. Free forever, 100K requests/day.',
    body: `# Cron Monitor

Self-hosted cron job monitoring with Cloudflare Workers. A free alternative to Healthchecks.io and Cronitor.

## Why Cron Monitor?

Healthchecks.io costs $3-108/year. Cron Monitor is free forever.

- **Ping Endpoint** — Simple GET request from your cron job
- **Grace Period** — Alert if no ping within X minutes
- **Webhook Alerts** — Get notified when jobs fail
- **Dashboard** — View all monitors and recent pings
- **100% Free** — Cloudflare Workers free tier: 100k requests/day
- **Open Source** — MIT License, self-hosted

## Quick Start

\`\`\`bash
# Clone and deploy
git clone https://github.com/ozxc44/cron-monitor.git
cd cron-monitor
npm install

# Create D1 database
wrangler d1 create cron-monitor-db

# Update wrangler.toml with database ID
# Then initialize schema
wrangler d1 execute cron-monitor-db --file=schema.sql

# Deploy
npm run deploy
\`\`\`

## Usage

### Create a Monitor

\`\`\`bash
curl -X POST https://your-worker.workers.dev/monitors \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Daily Backup",
    "grace_minutes": 60,
    "alert_webhook": "https://your-webhook-url"
  }'
\`\`\`

### Add to Crontab

\`\`\`bash
# Run daily at 2 AM, ping after completion
0 2 * * * /path/to/backup.sh && curl -s "https://your-worker.workers.dev/uuid-here/ping" || true
\`\`\`

## Comparison

| Feature | Cron Monitor | Healthchecks.io |
|---------|--------------|-----------------|
| Price | Free (CF tier) | $3-108/year |
| Self-hosted | Yes | No |
| Webhook alerts | Yes | Yes |
| Custom domain | Yes | Paid only |

## Links

- [GitHub Repository](https://github.com/ozxc44/cron-monitor)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['cloudflare', 'workers', 'monitoring', 'cron', 'devops', 'serverless', 'opensource']
  },

  bluesky: {
    text: `🚀 Cron Monitor — Free alternative to Healthchecks.io

Self-hosted cron job monitoring with Cloudflare Workers.

100K requests/day free forever.

github.com/ozxc44/cron-monitor

#serverless #devops #monitoring #opensource`
  },

  mastodon: {
    status: `🚀 Cron Monitor — Free alternative to Healthchecks.io

Self-hosted cron job monitoring with Cloudflare Workers. 100K requests/day free forever.

github.com/ozxc44/cron-monitor

#serverless #devops #monitoring #opensource`
  },

  discord: {
    description: 'Self-hosted cron job monitoring with Cloudflare Workers. Free forever alternative to Healthchecks.io.'
  }
};

/**
 * Status Widget Content
 */
export const statusWidget = {
  devto: {
    title: 'Status Widget — Free Self-Hosted Alternative to Statuspage.io',
    description: 'Self-hosted HTTP monitoring with embeddable status widget. Save $49/month.',
    body: `# Status Widget

Self-hosted HTTP monitoring with embeddable status widget. Free, lightweight, privacy-focused.

## Why Status Widget?

**Statuspage.io costs $49/month.** That's too much when you're starting out.

**Status Widget is free forever.** Self-host it, embed it, own your data.

## Features

| Feature | Description |
|---------|-------------|
| **Real-time Monitoring** | Check any HTTP endpoint every 60 seconds |
| **Embeddable Widget** | Add status to your site with one line of code |
| **Response Time** | See how fast your site responds |
| **History** | Check past status changes |
| **Uptime %** | Know your availability |

## Quick Start

\`\`\`bash
git clone https://github.com/ozxc44/status-widget.git
cd status-widget
npm install
npm start
\`\`\`

Visit http://localhost:3001

## Embed on Your Site

\`\`\`html
<script src="https://your-domain.com/widget.js?url=example.com"></script>
<div id="status-widget"></div>
\`\`\`

## Comparison

| | Status Widget | Statuspage.io | Uptime Kuma |
|---|---|---|---|
| **Price** | Free | $49+/mo | Free (self-hosted) |
| **Hosted** | No | Yes | No |
| **Setup Time** | 30 sec | 5 min | 10+ min |
| **Widget** | Yes | Yes | No |

## Links

- [GitHub Repository](https://github.com/ozxc44/status-widget)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['monitoring', 'uptime', 'statuspage', 'opensource', 'javascript', 'webdev']
  },

  bluesky: {
    text: `🚀 Status Widget — Free alternative to Statuspage.io

Save $49/month. Self-hosted HTTP monitoring with embeddable widget.

github.com/ozxc44/status-widget

#opensource #monitoring #webdev`
  },

  mastodon: {
    status: `🚀 Status Widget — Free alternative to Statuspage.io

Save $49/month. Self-hosted HTTP monitoring with embeddable widget.

github.com/ozxc44/status-widget

#opensource #monitoring #webdev`
  },

  discord: {
    description: 'Self-hosted HTTP monitoring with embeddable status widget. Free alternative to Statuspage.io ($49/mo).'
  }
};

/**
 * FlatPDF API Content
 */
export const flatpdfApi = {
  devto: {
    title: 'FlatPDF API — Self-Hosted HTML to PDF Conversion',
    description: 'Free self-hosted alternative to cloud PDF services. Docker-based, runs anywhere.',
    body: `# FlatPDF API

Self-hosted HTML to PDF conversion API. Simple. Fast. Yours.

## Why FlatPDF?

Cloud APIs charge $0.01-0.10 per page. That adds up fast.

FlatPDF is **free forever** when self-hosted.

| Problem | FlatPDF Solution |
|---------|------------------|
| Cloud APIs charge per page | **Free forever** when self-hosted |
| Data leaves your infrastructure | **Your server, your data** |
| Monthly subscriptions add up | **One-time setup, zero ongoing cost** |
| Vendor lock-in | **Open source, Docker-based, portable** |

## Quick Start

\`\`\`bash
git clone https://github.com/ozxc44/flatpdf-api.git
cd flatpdf-api
docker compose up -d
\`\`\`

That's it! Your API is running at \`http://localhost:8000\`

## API Usage

\`\`\`bash
curl -X POST http://localhost:8000/convert \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer your-api-key" \\
  -d '{
    "html": "<h1>Invoice #123</h1><p>Amount: $99.00</p>",
    "options": {
      "format": "A4",
      "margin": "1cm"
    }
  }'
\`\`\`

## Use Cases

- **Invoices & Receipts** — E-commerce platforms
- **Contracts** — SaaS agreement generation
- **Certificates** — Course completion badges
- **Reports** — Analytics dashboards export
- **Labels** — Shipping and logistics

## Links

- [GitHub Repository](https://github.com/ozxc44/flatpdf-api)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['pdf', 'api', 'python', 'docker', 'selfhosted', 'opensource', 'developer-tools']
  },

  bluesky: {
    text: `🚀 FlatPDF API — Self-hosted HTML to PDF

Free forever. No per-page fees.

Your server, your data, your PDFs.

github.com/ozxc44/flatpdf-api

#python #docker #api #opensource`
  },

  mastodon: {
    status: `🚀 FlatPDF API — Self-hosted HTML to PDF conversion

Free forever, no per-page fees. Your server, your data, your PDFs.

github.com/ozxc44/flatpdf-api

#python #docker #API #opensource`
  },

  discord: {
    description: 'Self-hosted HTML to PDF conversion API. Free forever alternative to cloud PDF services.'
  }
};

/**
 * Queue Monitor Content
 */
export const queueMonitor = {
  devto: {
    title: 'Queue Monitor — Because Monitoring Dashboards Don\'t Send 3am Texts',
    description: 'Queue alerting that actually wakes you up. For BullMQ, RQ, Celery, Sidekiq.',
    body: `# Queue Monitor

Queue alerting that actually wakes you up at 3am.

## The Problem

You deploy at 5pm. Everything looks great.

At 11pm, your email queue starts backing up. A worker crashes, memory leaks, and the queue silently dies.

You don't know. You're asleep.

At 8am, your inbox is full of "where's my confirmation email?" messages.

**The problem isn't that you lack monitoring.** You have Flower running. The problem is that **monitoring doesn't wake you up.**

## The Solution

**Queue Monitor** - A service that alerts you when something goes wrong:

- 🔔 **Queue Depth Alerts** - Know when queues back up before it's too late
- ❌ **Failed Job Tracking** - Aggregate and alert on repeated failures
- 💓 **Worker Heartbeat** - Get notified when workers go down
- ⚡ **Simple Setup** - 5 lines of code, no complex agents

## How We're Different

| | Flower / Horizon / Bull Board | Queue Monitor |
|---|---|---|
| Great Dashboard | ✅ | ✅ |
| Proactive Alerts | ❌ | ✅ |
| Wakes you up at 3am | ❌ | ✅ |

## Pricing

Starting at **$9/mo** - Less than an hour of your time is worth.

| Plan | Queues | Alerts | Price |
|------|--------|--------|-------|
| Free | 1 | Email only | $0 |
| Pro | 5 | Email + Slack | $9/mo |
| Team | Unlimited | Email + Slack + Webhook | $30/mo |

## Supported Technologies

- **Python**: RQ, Celery
- **Node.js**: BullMQ, Bull
- **Ruby**: Sidekiq
- **PHP**: Laravel Queue

## Links

- [Website](https://ozxc44.github.io/queue-monitor-dev/)
- [GitHub Repository](https://github.com/ozxc44/queue-monitor-dev)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['queue', 'monitoring', 'alerts', 'devops', 'bullmq', 'celery', 'rq']
  },

  bluesky: {
    text: `🚀 Queue Monitor — Alerting that wakes you up at 3am

Monitoring dashboards don't send texts. Queue Monitor does.

For BullMQ, RQ, Celery, Sidekiq.

github.com/ozxc44/queue-monitor-dev

#devops #queue #monitoring`
  },

  mastodon: {
    status: `🚀 Queue Monitor — Alerting that wakes you up at 3am

Monitoring dashboards don't send texts. Queue Monitor does. For BullMQ, RQ, Celery, Sidekiq.

github.com/ozxc44/queue-monitor-dev

#devops #queue #monitoring`
  },

  discord: {
    description: 'Queue alerting that actually wakes you up at 3am. Depth alerts, failed job tracking, worker heartbeat.'
  }
};

/**
 * Auto-Promoter Content
 */
export const autoPromoter = {
  devto: {
    title: 'Auto-Promoter — Cross-Post to Dev.to, Bluesky, Mastodon',
    description: 'Automated promotion tool for open source projects. One command, four platforms.',
    body: `# Auto-Promoter

Automated promotion tool for open source projects. Publish your projects to Dev.to, Hashnode, Bluesky, and Mastodon with a single command.

## The Problem

Promoting open source projects is tedious. You need to:
- Write blog posts
- Post on social media
- Engage with communities
- Track engagement

All while trying to actually build the thing.

## The Solution

Auto-Promoter automates the busy work:

- **One Command** — Promote to all platforms at once
- **Templates** — Project-specific content generation
- **GitHub Actions** — Auto-post on releases
- **Zero Dependencies** — Native Node.js fetch

## Quick Start

\`\`\`bash
# Clone
git clone https://github.com/ozxc44/auto-promoter.git
cd auto-promoter

# Install
npm install

# Configure
cp .env.example .env
# Edit .env with your API keys

# Run
npm run all
\`\`\`

## Supported Platforms

| Platform | Type | Status |
|----------|------|--------|
| Dev.to | Blog | ✅ Full API |
| Hashnode | Blog | ✅ Full API |
| Bluesky | Social | ✅ Full API |
| Mastodon | Social | ✅ Full API |

## GitHub Actions Integration

Add to your \`.github/workflows/promote.yml\`:

\`\`\`yaml
on:
  release:
    types: [published]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ozxc44/auto-promoter@v1
        with:
          devto_api_key: \${{ secrets.DEVTO_API_KEY }}
          bluesky_password: \${{ secrets.BLUESKY_APP_PASSWORD }}
\`\`\`

Every release automatically promoted!

## Links

- [GitHub Repository](https://github.com/ozxc44/auto-promoter)
- [npm Package](https://www.npmjs.com/package/auto-promoter)

---

*This post was generated by Auto-Promoter (meta!)*`,
    tags: ['javascript', 'automation', 'devtools', 'opensource', 'socialmedia', 'marketing', 'cli']
  },

  bluesky: {
    text: `🚀 Auto-Promoter — Cross-post to Dev.to, Bluesky, Mastodon

One command promotes your open source project to 4 platforms.

GitHub Actions integration included.

github.com/ozxc44/auto-promoter

#opensource #automation #developer-tools`
  },

  mastodon: {
    status: `🚀 Auto-Promoter — Cross-post to Dev.to, Bluesky, Mastodon

One command promotes your open source project to 4 platforms. GitHub Actions integration included.

github.com/ozxc44/auto-promoter

#opensource #automation #developer-tools`
  },

  discord: {
    description: 'Automated promotion tool for open source projects. Publish to 4 platforms with one command.'
  }
};

/**
 * Get template by project name
 */
export function getTemplate(projectName) {
  const templates = {
    'badge-generator': badgeGenerator,
    'badge-generator': badgeGenerator,
    'status-badge-2': statusBadge2,
    'status-badge-2.0': statusBadge2,
    'status-badge': statusBadge2,
    'docuapi': docuapi,
    'docu-api': docuapi,
    'auto-promoter': autoPromoter,
    'auto_promoter': autoPromoter,
    'cron-monitor': cronMonitor,
    'cron_monitor': cronMonitor,
    'status-widget': statusWidget,
    'status_widget': statusWidget,
    'flatpdf-api': flatpdfApi,
    'flatpdf_api': flatpdfApi,
    'flatpdf': flatpdfApi,
    'queue-monitor': queueMonitor,
    'queue_monitor': queueMonitor,
    'queue-monitor-dev': queueMonitor,
    'email-cleanup': null, // No English template yet
    'email_cleanup': null,
    'form-to-pdf': null, // No English template yet
    'form_to_pdf': null,
    'status-widget-cf': statusWidget,
    'status_widget_cf': statusWidget,
    'tiktok-compliance-scanner': null, // No template yet
    'tiktok_compliance_scanner': null
  };

  // Try exact match first
  if (templates[projectName]) {
    return templates[projectName];
  }

  // Try case-insensitive match
  const key = Object.keys(templates).find(k => k.toLowerCase() === projectName.toLowerCase());
  return templates[key];
}

/**
 * Get default template (generic)
 */
export function getDefaultTemplate() {
  return {
    devto: {
      title: '🚀 Check Out This Open Source Project',
      tags: ['opensource', 'javascript', 'webdev', 'showdev']
    },
    bluesky: {
      text: '🚀 Just published a new open source project! Check it out: #opensource'
    },
    mastodon: {
      status: '🚀 Just published a new open source project! #opensource'
    },
    discord: {
      description: 'A new open source project from Auto Company.'
    }
  };
}

export default {
  badgeGenerator,
  statusBadge2,
  docuapi,
  autoPromoter,
  cronMonitor,
  statusWidget,
  flatpdfApi,
  queueMonitor,
  getTemplate,
  getDefaultTemplate
};
