/**
 * Content Templates for Auto-Promoter
 * Project-specific content for better engagement
 */

/**
 * Badge Generator Content
 */
export const badgeGenerator = {
  devto: {
    title: 'Complete GitHub Badge Reference — Copy, Paste, Done',
    description: 'The complete badge reference for your GitHub README. 500+ badges, all CDN-hosted, free forever.',
    body: `# GitHub Badge Generator

The complete badge reference for your GitHub README. All badges are SVG-based, CDN-hosted, and free forever.

## Why This Project?

Most badge references are incomplete or scattered across multiple sites. This project brings together:

- **500+ badge examples** — All in one place
- **CDN-hosted** — Via Shields.io, no hosting needed
- **Copy-paste** — No editing required
- **Organized** — Logical categories for easy browsing

## Quick Start

\`\`\`markdown
[![Status](https://img.shields.io/badge/status-active-success)]()
[![License](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
\`\`\`

## Categories

| Category | Examples |
|----------|----------|
| Status | Active, Beta, Deprecated, Stable |
| Version | npm, PyPI, Cargo, Go |
| License | MIT, Apache, GPL, MPL |
| Platform | AWS, Vercel, Cloudflare, Railway |
| Language | JS, TS, Python, Rust, Go, Java |
| Build | GitHub Actions, CI, Tests |
| Quality | CodeFactor, Lint, Coverage |
| Social | Stars, Forks, Followers |
| Funding | GitHub Sponsors, Patreon |

## What Makes This Different

1. **Comprehensive** — Covers all major badge types
2. **Organized** — Logical categorization
3. **Ready to Use** — Copy the code, paste in your README
4. **Always Updated** — Live badges that show current status

## Use Cases

- **Open Source Projects** — Show build status, version, license
- **SaaS Products** — Display uptime, response time
- **Documentation Sites** — Add visual indicators
- **Personal Portfolios** — Showcase skills and tech stack

## Examples

\`\`\`markdown
# My Project

[![Status](https://img.shields.io/badge/status-active-success)]()
[![npm](https://img.shields.io/npm/v/my-package)](https://www.npmjs.com/package/my-package)
[![License](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

My awesome project description.
\`\`\`

## Links

- [GitHub Repository](https://github.com/ozxc44/badge-generator)
- [Full Reference](https://github.com/ozxc44/badge-generator#readme)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['javascript', 'github', 'opensource', 'webdev', 'documentation', 'badges', 'readme', 'developer-tools']
  },

  bluesky: {
    text: `🚀 Just published: GitHub Badge Generator

The complete badge reference for your README.

500+ badges, CDN-hosted, free forever.

github.com/ozxc44/badge-generator

#opensource #javascript #github #developer-tools`
  },

  mastodon: {
    status: `🚀 Just published: GitHub Badge Generator

The complete badge reference for your README. 500+ badges, all CDN-hosted, free forever.

github.com/ozxc44/badge-generator

#opensource #javascript #GitHub #developer-tools`
  },

  discord: {
    description: 'The complete badge reference for your GitHub README. 500+ badges, all CDN-hosted, free forever.'
  }
};

/**
 * Status Badge 2.0 Content
 */
export const statusBadge2 = {
  devto: {
    title: 'Status Badge 2.0 — Serverless Monitoring Widget',
    description: 'Zero-config status monitoring with Cloudflare Workers. Free forever, 100K requests/day.',
    body: `# Status Badge 2.0

A drop-in status widget for any website or API. One line of JavaScript, and you get real-time status monitoring.

## Why Status Badge 2.0?

Most status page solutions are overkill for simple monitoring. Status Badge 2.0 is:

- **Zero Infrastructure** — Runs on Cloudflare Workers edge
- **Free Forever** — 100K requests/day on free tier
- **One-Line Embed** — \`<script src="..."></script>\` and done
- **Shadow DOM** — Styles won't break your site
- **Edge-Fast** — Global CDN, <50ms responses

## Quick Start

### 1. Create a Monitor

\`\`\`bash
curl -X POST https://your-worker.workers.dev/api/monitors \\
  -H "Content-Type: application/json" \\
  -d '{"targetUrl": "https://api.example.com/health", "name": "My API"}'
\`\`\`

### 2. Embed on Your Site

\`\`\`html
<script src="https://your-worker.workers.dev/v1/YOUR_ID.js"></script>
\`\`\`

That's it! The badge shows:
- ✅ Current status (Online/Offline)
- ⏱️ Response time
- 📊 Uptime percentage (24h)

## Architecture

\`\`\`
User's Website
    ↓
<script src="badge.js">
    ↓
Shadow DOM Widget
    ↓
Cloudflare Worker (Edge)
    ↓
Cloudflare KV (Cache)
    ↓
Target API
\`\`\`

## Features

| Feature | Description |
|---------|-------------|
| Real-time | Updates every 60 seconds |
| Themes | Default, Dark, Minimal |
| JSON API | Get status data for custom UI |
| SVG Badge | Image format for READMEs |
| Webhooks | Coming soon |

## Use Cases

- **API Status** — Monitor REST/GraphQL endpoints
- **SaaS Dashboard** — Show service status to customers
- **CI/CD** — Display build/deployment status
- **Microservices** — Monitor multiple services

## Links

- [GitHub Repository](https://github.com/ozxc44/status-badge-2)
- [Live Demo](https://ozxc44.github.io/status-badge-2/)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['javascript', 'cloudflare', 'workers', 'serverless', 'monitoring', 'uptime', 'devops', 'api']
  },

  bluesky: {
    text: `🚀 Status Badge 2.0 — Serverless monitoring widget

One line of JavaScript = real-time status monitoring.

Runs on Cloudflare Workers edge.
Free forever (100K requests/day).

github.com/ozxc44/status-badge-2

#serverless #cloudflare #monitoring #javascript`
  },

  mastodon: {
    status: `🚀 Status Badge 2.0 — Serverless monitoring widget

One line of JavaScript gives you real-time status monitoring. Runs on Cloudflare Workers edge, free forever (100K requests/day).

github.com/ozxc44/status-badge-2

#serverless #Cloudflare #monitoring #JavaScript`
  },

  discord: {
    description: 'One-line JavaScript widget for real-time status monitoring. Runs on Cloudflare Workers edge, free forever.'
  }
};

/**
 * DocuAPI Content
 */
export const docuapi = {
  devto: {
    title: 'DocuAPI — Generate API Docs from OpenAPI Specs',
    description: 'CLI tool to generate beautiful API documentation from OpenAPI/Swagger specs.',
    body: `# DocuAPI

Generate beautiful API documentation from OpenAPI/Swagger specifications. Perfect for REST APIs, microservices, and backend services.

## Why DocuAPI?

Writing API documentation is tedious. DocuAPI automates it:

- **From OpenAPI** — Import existing specs
- **Beautiful Output** — Clean, readable HTML docs
- **Multiple Formats** — HTML, Markdown, PDF
- **Searchable** — Full-text search included
- **Host Anywhere** — Static files, no database needed

## Quick Start

\`\`\`bash
# Install
npm install -g docuapi

# Generate docs
docuapi generate openapi.json -o docs/

# Serve locally
docuapi serve docs/
\`\`\`

## Features

| Feature | Description |
|---------|-------------|
| OpenAPI 3.0 | Full specification support |
| Multiple Output | HTML, Markdown, PDF |
| Search | Client-side full-text search |
| Themes | Light/dark mode included |
| Examples | Auto-generate from specs |

## Input Example

\`\`\`yaml
openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: Success
\`\`\`

## Links

- [GitHub Repository](https://github.com/ozxc44/docuapi)

---

*This post was generated by Auto Company's Auto-Promoter*`,
    tags: ['api', 'documentation', 'openapi', 'swagger', 'cli', 'developer-tools', 'rest']
  },

  bluesky: {
    text: `🚀 DocuAPI — Generate API docs from OpenAPI specs

CLI tool that creates beautiful documentation from your OpenAPI/Swagger specs.

Supports HTML, Markdown, PDF outputs.

github.com/ozxc44/docuapi

#api #documentation #openapi #developer-tools`
  },

  mastodon: {
    status: `🚀 DocuAPI — Generate API docs from OpenAPI specs

CLI tool that creates beautiful documentation from your OpenAPI/Swagger specs. Supports HTML, Markdown, PDF outputs.

github.com/ozxc44/docuapi

#API #documentation #OpenAPI #developer-tools`
  },

  discord: {
    description: 'CLI tool to generate beautiful API documentation from OpenAPI/Swagger specifications.'
  }
};

/**
 * Auto-Promoter Content
 */
export const autoPromoter = {
  devto: {
    title: 'Auto-Promoter — Cross-Post to Dev.to, Bluesky, Mastodon',
    description: 'Automated promotion tool for open source projects. One command, four platforms.',
    body: `# Auto-Promoter

Automated promotion tool for open source projects. Publish your projects to Dev.to, Hashnode, Bluesky, and Mastodon with a single command.

## The Problem

Promoting open source projects is tedious. You need to:
- Write blog posts
- Post on social media
- Engage with communities
- Track engagement

All while trying to actually build the thing.

## The Solution

Auto-Promoter automates the busy work:

- **One Command** — Promote to all platforms at once
- **Templates** — Project-specific content generation
- **GitHub Actions** — Auto-post on releases
- **Zero Dependencies** — Native Node.js fetch

## Quick Start

\`\`\`bash
# Clone
git clone https://github.com/ozxc44/auto-promoter.git
cd auto-promoter

# Install
npm install

# Configure
cp .env.example .env
# Edit .env with your API keys

# Run
npm run all
\`\`\`

## Supported Platforms

| Platform | Type | Status |
|----------|------|--------|
| Dev.to | Blog | ✅ Full API |
| Hashnode | Blog | ✅ Full API |
| Bluesky | Social | ✅ Full API |
| Mastodon | Social | ✅ Full API |

## GitHub Actions Integration

Add to your \`.github/workflows/promote.yml\`:

\`\`\`yaml
on:
  release:
    types: [published]

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ozxc44/auto-promoter@v1
        with:
          devto_api_key: \${{ secrets.DEVTO_API_KEY }}
          bluesky_password: \${{ secrets.BLUESKY_APP_PASSWORD }}
\`\`\`

Every release automatically promoted!

## Links

- [GitHub Repository](https://github.com/ozxc44/auto-promoter)
- [npm Package](https://www.npmjs.com/package/auto-promoter)

---

*This post was generated by Auto-Promoter (meta!)*`,
    tags: ['javascript', 'automation', 'devtools', 'opensource', 'socialmedia', 'marketing', 'cli']
  },

  bluesky: {
    text: `🚀 Auto-Promoter — Cross-post to Dev.to, Bluesky, Mastodon

One command promotes your open source project to 4 platforms.

GitHub Actions integration included.

github.com/ozxc44/auto-promoter

#opensource #automation #developer-tools`
  },

  mastodon: {
    status: `🚀 Auto-Promoter — Cross-post to Dev.to, Bluesky, Mastodon

One command promotes your open source project to 4 platforms. GitHub Actions integration included.

github.com/ozxc44/auto-promoter

#opensource #automation #developer-tools`
  },

  discord: {
    description: 'Automated promotion tool for open source projects. Publish to 4 platforms with one command.'
  }
};

/**
 * Get template by project name
 */
export function getTemplate(projectName) {
  const templates = {
    'badge-generator': badgeGenerator,
    'badge-generator': badgeGenerator,
    'status-badge-2': statusBadge2,
    'status-badge-2.0': statusBadge2,
    'docuapi': docuapi,
    'auto-promoter': autoPromoter
  };

  // Try exact match first
  if (templates[projectName]) {
    return templates[projectName];
  }

  // Try case-insensitive match
  const key = Object.keys(templates).find(k => k.toLowerCase() === projectName.toLowerCase());
  return templates[key];
}

/**
 * Get default template (generic)
 */
export function getDefaultTemplate() {
  return {
    devto: {
      title: '🚀 Check Out This Open Source Project',
      tags: ['opensource', 'javascript', 'webdev', 'showdev']
    },
    bluesky: {
      text: '🚀 Just published a new open source project! Check it out: #opensource'
    },
    mastodon: {
      status: '🚀 Just published a new open source project! #opensource'
    },
    discord: {
      description: 'A new open source project from Auto Company.'
    }
  };
}

export default {
  badgeGenerator,
  statusBadge2,
  docuapi,
  autoPromoter,
  getTemplate,
  getDefaultTemplate
};
